server:
  port: 8001
spring:
  jpa:
    database: mysql
  datasource:
    url: jdbc:mysql://db:3306/mwpdb
    username: root
    password: redacted
  application:
    name: PROJECTS-SERVICE

logging:
  logback:
    appender:
      name: "fileAppender"
    encoder:
      pattern: "%d [%thread] %-5level  %logger{35} - %msg%n"
    rollingpolicy:
      file-name-pattern: "/logs/projects-service/logFile.%d{yyyy-MM-dd}.log"
      max-history: 3
  level:
    root: info

management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: "/actuator"

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://service-registry:8761/eureka/
  instance:
    hostname: localhost
