server:
  port: 8080

spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  application:
    name: my-web-page

management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: "/act"



eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://service-registry:8761/eureka/
  instance:
    hostname: service-registry