server:
  port: 9000
spring:
  application:
    name: api-gateway
  cloud:
    discovery:
      enabled: true
    gateway:
      routes:
        - id: projects-service
          uri: http://projects-service:8001
          predicates:
            - Path=/projects/**
        - id: user-service
          uri: http://user-service:8002
          predicates:
            - Path=/users/**
        - id: email-service
          uri: http://email-service:8004
          predicates:
            - Path=/emails/**
        - id: issue-tracker-service
          uri: http://issue-tracker-service:9091
          predicates:
            - Path=/issue/**

logging:
  logback:
    appender:
      name: "fileAppender"
    encoder:
      pattern: "%d [%thread] %-5level  %logger{35} - %msg%n"
    rollingpolicy:
      file-name-pattern: "/logs/api-gateway/logFile.%d{yyyy-MM-dd}.log"
      max-history: 3
  level:
    root: info

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://service-registry:8761/eureka/
  instance:
    hostname: service-registry