server:
  port: 9000
spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: PROJECTS-SERVICE
          uri: lb://PROJECTS-SERVICE
          predicates:
            - Path=/projects/**
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost