server:
  port: 9000
spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: PROJECTS-SERVICE
          uri: lb://PROJECTS-SERVICE
          predicates:
            - Path=/projectsdb/**
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/userdb/**
        - id: FRONTEND
          uri: lb://FRONTEND
          predicates:
            - Path=/**
        - id: REGISTER-SERVICE
          uri: lb://REGISTER-SERVICE
          predicates:
            - Path=/register/**


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost